version: '3.7'

services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=12345
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - '5432:5432'

